# LOAD DATASET

In [1]:
from google.colab import files

uploaded = files.upload()

Saving claims_main.csv to claims_main.csv

In [2]:
import pandas as pd
import sqlite3

In [7]:
df = pd.read_csv("claims_main.csv")

In [3]:
conn = sqlite3.connect("claims.db")

In [10]:
df.to_sql("claims", conn, if_exists="replace", index=False)

120000

DATA EXPLORATION

In [ ]:
query = """
SELECT *
FROM claims
LIMIT 10;
"""

pd.read_sql(query, conn)

,claim_id,claim_submission_date,claim_year,claim_quarter,payer_type,provider_specialty,place_of_service_code,place_of_service_desc,cpt_code,modifier,...,prior_auth_obtained,prior_auth_number,documentation_completeness,claim_amount_usd,outcome,denial_reason_code,denial_category,dataset_version,synthetic_flag,generation_date
0,e46071e9-0fe0-42d8-ab46-dbb0c48341c4,2022-04-22,2022,Q2,Commercial_PPO,Emergency_Medicine,23,Emergency_Room,99283,None,...,NaN,None,0.40,656.22,denied,CO-4,coding_error,2.0,1,2026-04-28
1,a641a4ce-38d4-4467-a9d3-d4970735ecc0,2022-07-24,2022,Q3,Medicare_FFS,Internal_Medicine,11,Office,99215,25,...,NaN,None,0.37,332.89,denied,CO-97,duplicate,2.0,1,2026-04-28
2,2bd53273-5f36-46ad-b777-0035afd1e2e7,2022-08-24,2022,Q3,Commercial_EPO,Cardiology,2,Telehealth,93000,None,...,NaN,None,0.65,185.97,denied,CO-4,bundling,2.0,1,2026-04-28
3,72df5380-e03a-4ae9-a1e0-3d3aadf13daf,2021-07-26,2021,Q3,Commercial_PPO,Physical_Therapy,11,Office,97530,59,...,NaN,None,0.85,157.25,paid,None,None,2.0,1,2026-04-28
4,9eb5d58c-3f62-40a9-971f-37855af76d48,2021-12-01,2021,Q4,Medicaid_Managed,Obstetrics_Gynecology,23,Emergency_Room,59400,None,...,0.0,None,0.38,8991.46,denied,CO-16,auth_missing,2.0,1,2026-04-28
5,c1d4fcd4-e5de-4af8-9277-f11ab20ab6d8,2022-10-07,2022,Q4,Medicare_Advantage,Primary_Care,21,Inpatient_Hospital,99396,None,...,0.0,None,0.39,257.02,denied,CO-11,medical_necessity,2.0,1,2026-04-28
6,3f72ad2d-7c84-497f-948a-507424c85f62,2021-10-11,2021,Q4,Medicaid_Managed,Physical_Therapy,11,Office,97140,None,...,0.0,None,0.40,94.31,denied,N-130,auth_missing,2.0,1,2026-04-28
7,29cf2659-68c5-4957-a8d9-9235617c58be,2024-02-08,2024,Q1,Medicare_FFS,Emergency_Medicine,2,Telehealth,99283,25,...,NaN,None,0.97,715.63,paid,None,None,2.0,1,2026-04-28
8,9bbcb48e-1812-4725-8a69-23f54a55237c,2023-11-06,2023,Q4,Medicare_FFS,Neurology,11,Office,64483,25,...,0.0,None,0.68,3342.99,denied,CO-109,medical_necessity,2.0,1,2026-04-28
9,51b09cda-ead6-425b-832a-3ede5d17267b,2022-09-22,2022,Q3,Commercial_HMO,Cardiology,11,Office,99214,25,...,1.0,PA-217301,0.40,399.00,denied,CO-109,medical_necessity,2.0,1,2026-04-28

In [ ]:
query = """
SELECT COUNT(*) AS Total_Claims
FROM claims;
"""

pd.read_sql(query, conn)

   Total_Claims
0        120000

In [ ]:
query = """
PRAGMA table_info(claims);
"""

pd.read_sql(query, conn)

    cid                        name     type  notnull dflt_value  pk
0     0                    claim_id     TEXT        0       None   0
1     1       claim_submission_date     TEXT        0       None   0
2     2                  claim_year  INTEGER        0       None   0
3     3               claim_quarter     TEXT        0       None   0
4     4                  payer_type     TEXT        0       None   0
5     5          provider_specialty     TEXT        0       None   0
6     6       place_of_service_code  INTEGER        0       None   0
7     7       place_of_service_desc     TEXT        0       None   0
8     8                    cpt_code     TEXT        0       None   0
9     9                    modifier     TEXT        0       None   0
10   10            primary_icd10_dx     TEXT        0       None   0
11   11          primary_icd10_desc     TEXT        0       None   0
12   12          secondary_icd10_dx     TEXT        0       None   0
13   13          secondary_dx_count  INTEGER        0       None   0
14   14         prior_auth_required  INTEGER        0       None   0
15   15         prior_auth_obtained  INTEGER        0       None   0
16   16           prior_auth_number     TEXT        0       None   0
17   17  documentation_completeness     REAL        0       None   0
18   18            claim_amount_usd     REAL        0       None   0
19   19                     outcome     TEXT        0       None   0
20   20          denial_reason_code     TEXT        0       None   0
21   21             denial_category     TEXT        0       None   0
22   22             dataset_version     REAL        0       None   0
23   23              synthetic_flag  INTEGER        0       None   0
24   24             generation_date     TEXT        0       None   0

In [ ]:
query= '''
select distinct outcome
from claims;
'''

pd,pd.read_sql_query(query,conn)

(<module 'pandas' from '/usr/local/lib/python3.12/dist-packages/pandas/__init__.py'>,
        outcome
 0       denied
 1         paid
 2      pending
 3  partial_pay)

In [ ]:
query = """
SELECT outcome,
       COUNT(*) AS Total
FROM claims
GROUP BY outcome;
"""

pd.read_sql(query, conn)

       outcome  Total
0       denied  33664
1         paid  62379
2  partial_pay  15469
3      pending   8488

In [ ]:
query ='''
select payer_type,
count(*) as total_claims
from claims
group by payer_type
order by total_claims desc;
'''

pd.read_sql(query,conn)

           payer_type  total_claims
0      Commercial_PPO         30016
1        Medicare_FFS         26300
2  Medicare_Advantage         21758
3    Medicaid_Managed         17996
4      Commercial_HMO         15458
5      Commercial_EPO          8472

In [ ]:
query ='''
select distinct provider_specialty
from claims;
'''

pd.read_sql(query,conn)

       provider_specialty
0      Emergency_Medicine
1       Internal_Medicine
2              Cardiology
3        Physical_Therapy
4   Obstetrics_Gynecology
5            Primary_Care
6               Neurology
7                Oncology
8      Orthopedic_Surgery
9       Behavioral_Health
10              Radiology
11       Gastroenterology
12            Pulmonology

In [ ]:
query='''
select provider_specialty,
count(*)from claims
group by provider_specialty
order by count(*)desc;
'''

pd.read_sql(query,conn)

       provider_specialty  count(*)
0      Emergency_Medicine     16738
1       Internal_Medicine     14386
2              Cardiology     12078
3      Orthopedic_Surgery     10658
4       Behavioral_Health      9379
5               Radiology      8471
6                Oncology      8458
7        Gastroenterology      7410
8            Primary_Care      7313
9               Neurology      7075
10            Pulmonology      6075
11       Physical_Therapy      6038
12  Obstetrics_Gynecology      5921

In [ ]:
query = """
Select distinct denial_reason_code
from claims
where denial_reason_code IS NOT NULL;
"""

pd.read_sql(query, conn)

   denial_reason_code
0                CO-4
1               CO-97
2               CO-16
3               CO-11
4               N-130
5              CO-109
6               CO-50
7               PR-27
8               OA-18
9               CO-22
10              CO-18
11             PR-204
12             CO-119
13              CO-29
14              OA-23

In [ ]:
query = """
SELECT DISTINCT outcome
FROM claims;
"""

pd.read_sql(query, conn)

       outcome
0       denied
1         paid
2      pending
3  partial_pay

In [ ]:
query = """
SELECT COUNT(*)
FROM claims
WHERE denial_reason_code IS NOT NULL;
"""

pd.read_sql(query, conn)

   COUNT(*)
0     33664

In [ ]:
query = """
SELECT outcome,
       denial_reason_code
FROM claims
LIMIT 20;
"""

pd.read_sql(query, conn)

    outcome denial_reason_code
0    denied               CO-4
1    denied              CO-97
2    denied               CO-4
3      paid               None
4    denied              CO-16
5    denied              CO-11
6    denied              N-130
7      paid               None
8    denied             CO-109
9    denied             CO-109
10  pending               None
11     paid               None
12   denied             CO-109
13     paid               None
14     paid               None
15     paid               None
16     paid               None
17     paid               None
18     paid               None
19     paid               None

In [ ]:
query = """
SELECT denial_reason_code,
       COUNT(*) AS Total
FROM claims
WHERE outcome='denied'
GROUP BY denial_reason_code
ORDER BY Total DESC;
"""

pd.read_sql(query, conn)

   denial_reason_code  Total
0               CO-11   4236
1               CO-16   3928
2              CO-109   3654
3               CO-97   3214
4                CO-4   2354
5              CO-119   2354
6               CO-50   2341
7               CO-29   2315
8              PR-204   2065
9               N-130   2043
10              PR-27   1429
11              CO-22   1331
12              OA-18    900
13              CO-18    889
14              OA-23    611

KPI ANALYSIS

In [12]:
pd.options.display.float_format = '{:,.2f}'.format

In [13]:
query = """
SELECT SUM(claim_amount_usd) AS Total_Claim_Amount
FROM claims;
"""

pd.read_sql(query, conn)

   Total_Claim_Amount
0      266,829,762.19

In [14]:
query = """
SELECT ROUND(AVG(claim_amount_usd),2) AS Average_Claim
FROM claims;
"""

pd.read_sql(query, conn)

   Average_Claim
0       2,223.58

In [15]:
query = """
SELECT MAX(claim_amount_usd) AS Highest_Claim
FROM claims;
"""

pd.read_sql(query, conn)

   Highest_Claim
0      37,918.58

In [16]:
query = """
SELECT MIN(claim_amount_usd) AS Highest_Claim
FROM claims;
"""

pd.read_sql(query, conn)

   Highest_Claim
0          52.24

In [17]:
query = """
SELECT outcome,
       SUM(claim_amount_usd) AS Total_Revenue
FROM claims
GROUP BY outcome
ORDER BY Total_Revenue DESC;
"""

pd.read_sql(query, conn)

       outcome  Total_Revenue
0         paid 139,055,114.84
1       denied  74,132,368.07
2  partial_pay  34,895,778.49
3      pending  18,746,500.79

In [18]:
query = """
SELECT payer_type,
       ROUND(AVG(claim_amount_usd),2) AS Avg_Claim
FROM claims
GROUP BY payer_type
ORDER BY Avg_Claim DESC;
"""

pd.read_sql(query, conn)

           payer_type  Avg_Claim
0      Commercial_PPO   2,625.38
1      Commercial_EPO   2,463.15
2      Commercial_HMO   2,407.83
3  Medicare_Advantage   2,104.62
4        Medicare_FFS   2,029.21
5    Medicaid_Managed   1,710.25

In [19]:
query = """
SELECT provider_specialty,
       SUM(claim_amount_usd) AS Revenue
FROM claims
GROUP BY provider_specialty
ORDER BY Revenue DESC;
"""

pd.read_sql(query, conn)

       provider_specialty       Revenue
0      Orthopedic_Surgery 86,518,546.22
1              Cardiology 45,763,830.61
2   Obstetrics_Gynecology 29,808,134.62
3      Emergency_Medicine 21,520,019.28
4        Gastroenterology 20,946,659.34
5                Oncology 20,806,724.98
6               Radiology 16,227,334.02
7               Neurology  8,627,066.44
8             Pulmonology  7,401,028.64
9       Internal_Medicine  4,034,367.22
10      Behavioral_Health  2,342,718.96
11           Primary_Care  1,898,430.35
12       Physical_Therapy    934,901.51

In [20]:
query = """
SELECT SUM(claim_amount_usd) AS Denied_Amount
FROM claims
WHERE outcome='denied';
"""

pd.read_sql(query, conn)

   Denied_Amount
0  74,132,368.07

In [21]:
query = """
SELECT SUM(claim_amount_usd) AS Paid_Amount
FROM claims
WHERE outcome='paid';
"""

pd.read_sql(query, conn)

     Paid_Amount
0 139,055,114.84

In [22]:
query = """
SELECT outcome,
       ROUND(AVG(claim_amount_usd),2) AS Avg_Claim
FROM claims
GROUP BY outcome;
"""

pd.read_sql(query, conn)

       outcome  Avg_Claim
0       denied   2,202.13
1         paid   2,229.20
2  partial_pay   2,255.85
3      pending   2,208.59

BUSINESS ANALYSIS
[PART 1 :OUTCOME ANALYSIS ]

In [24]:
#How many claims are Paid, Denied and Pending?
query = """
SELECT outcome,
       COUNT(*) AS Total_Claims
FROM claims
GROUP BY outcome
ORDER BY Total_Claims DESC;
"""

pd.read_sql(query, conn)

       outcome  Total_Claims
0         paid         62379
1       denied         33664
2  partial_pay         15469
3      pending          8488

In [25]:
#What percentage of claims belong to each outcome?
query = """
SELECT outcome,
       COUNT(*) AS Total_Claims,
       ROUND(COUNT(*) * 100.0 /
       (SELECT COUNT(*) FROM claims),2) AS Percentage
FROM claims
GROUP BY outcome
ORDER BY Percentage DESC;
"""

pd.read_sql(query, conn)

       outcome  Total_Claims  Percentage
0         paid         62379       51.98
1       denied         33664       28.05
2  partial_pay         15469       12.89
3      pending          8488        7.07

In [26]:
#What is the total claim amount for each outcome?
query = """
SELECT outcome,
       ROUND(SUM(claim_amount_usd),2) AS Total_Amount
FROM claims
GROUP BY outcome
ORDER BY Total_Amount DESC;
"""

pd.read_sql(query, conn)

       outcome   Total_Amount
0         paid 139,055,114.84
1       denied  74,132,368.07
2  partial_pay  34,895,778.49
3      pending  18,746,500.79

In [27]:
#What is the average claim amount by outcome?
query = """
SELECT outcome,
       ROUND(AVG(claim_amount_usd),2) AS Average_Claim
FROM claims
GROUP BY outcome
ORDER BY Average_Claim DESC;
"""

pd.read_sql(query, conn)

       outcome  Average_Claim
0  partial_pay       2,255.85
1         paid       2,229.20
2      pending       2,208.59
3       denied       2,202.13

In [28]:
#Highest claim amount in each outcome
query = """
SELECT outcome,
       MAX(claim_amount_usd) AS Highest_Claim
FROM claims
GROUP BY outcome;
"""

pd.read_sql(query, conn)

       outcome  Highest_Claim
0       denied      37,897.59
1         paid      37,796.11
2  partial_pay      37,632.91
3      pending      37,918.58

In [29]:
#Lowest claim amount in each outcome
query = """
SELECT outcome,
       MIN(claim_amount_usd) AS Lowest_Claim
FROM claims
GROUP BY outcome;
"""

pd.read_sql(query, conn)

       outcome  Lowest_Claim
0       denied         52.80
1         paid         52.24
2  partial_pay         58.29
3      pending         66.58

In [30]:
#Total denied amount
query = """
SELECT ROUND(SUM(claim_amount_usd),2) AS Denied_Amount
FROM claims
WHERE outcome='denied';
"""

pd.read_sql(query, conn)

   Denied_Amount
0  74,132,368.07

In [31]:
#Total paid amount
query = """
SELECT ROUND(SUM(claim_amount_usd),2) AS Paid_Amount
FROM claims
WHERE outcome='paid';
"""

pd.read_sql(query, conn)

     Paid_Amount
0 139,055,114.84

PAYERS ANALYSIS

In [32]:
#Which payer processed the highest number of claims?
query = """
SELECT payer_type,
       COUNT(*) AS Total_Claims
FROM claims
GROUP BY payer_type
ORDER BY Total_Claims DESC;
"""

pd.read_sql(query, conn)

           payer_type  Total_Claims
0      Commercial_PPO         30016
1        Medicare_FFS         26300
2  Medicare_Advantage         21758
3    Medicaid_Managed         17996
4      Commercial_HMO         15458
5      Commercial_EPO          8472

In [33]:
#Which payer has the highest number of paid claims?
query = """
SELECT payer_type,
       COUNT(*) AS Paid_Claims
FROM claims
WHERE outcome='paid'
GROUP BY payer_type
ORDER BY Paid_Claims DESC;
"""

pd.read_sql(query, conn)

           payer_type  Paid_Claims
0      Commercial_PPO        15651
1        Medicare_FFS        13658
2  Medicare_Advantage        11335
3    Medicaid_Managed         9300
4      Commercial_HMO         8030
5      Commercial_EPO         4405

In [34]:
#Which payer denied the most claims?
query = """
SELECT payer_type,
       COUNT(*) AS Denied_Claims
FROM claims
WHERE outcome='denied'
GROUP BY payer_type
ORDER BY Denied_Claims DESC;
"""

pd.read_sql(query, conn)

           payer_type  Denied_Claims
0      Commercial_PPO           8338
1        Medicare_FFS           7378
2  Medicare_Advantage           6148
3    Medicaid_Managed           5130
4      Commercial_HMO           4324
5      Commercial_EPO           2346

In [35]:
#Which payer has the highest pending claims?
query = """
SELECT payer_type,
       COUNT(*) AS Pending_Claims
FROM claims
WHERE outcome='pending'
GROUP BY payer_type
ORDER BY Pending_Claims DESC;
"""

pd.read_sql(query, conn)

           payer_type  Pending_Claims
0      Commercial_PPO            2151
1        Medicare_FFS            1799
2  Medicare_Advantage            1546
3    Medicaid_Managed            1306
4      Commercial_HMO            1087
5      Commercial_EPO             599

In [40]:
#Which payer contributes the highest claim amount(TOTAL REVENUE BY PAYER)?
query = """
SELECT payer_type,
       ROUND(SUM(claim_amount_usd),2) AS Total_Revenue
FROM claims
GROUP BY payer_type
ORDER BY Total_Revenue DESC;
"""

pd.read_sql(query, conn)

           payer_type  Total_Revenue
0      Commercial_PPO  78,803,522.61
1        Medicare_FFS  53,368,320.86
2  Medicare_Advantage  45,792,265.74
3      Commercial_HMO  37,220,270.21
4    Medicaid_Managed  30,777,570.09
5      Commercial_EPO  20,867,812.68

In [37]:
#Which payer contributes the Average  claim amount?
query = """
SELECT payer_type,
       ROUND(AVG(claim_amount_usd),2) AS Average_Claim
FROM claims
GROUP BY payer_type
ORDER BY Average_Claim DESC;
"""

pd.read_sql(query, conn)

           payer_type  Average_Claim
0      Commercial_PPO       2,625.38
1      Commercial_EPO       2,463.15
2      Commercial_HMO       2,407.83
3  Medicare_Advantage       2,104.62
4        Medicare_FFS       2,029.21
5    Medicaid_Managed       1,710.25

In [39]:
#Highest Claim Amount by Payer
query = """
SELECT payer_type,
       MAX(claim_amount_usd) AS Highest_Claim
FROM claims
GROUP BY payer_type
ORDER BY Highest_Claim DESC;
"""

pd.read_sql(query, conn)

           payer_type  Highest_Claim
0      Commercial_PPO      37,918.58
1      Commercial_EPO      36,048.26
2      Commercial_HMO      34,940.19
3  Medicare_Advantage      31,117.34
4        Medicare_FFS      29,630.90
5    Medicaid_Managed      24,689.71

In [41]:
#Lowest Claim Amount by Payer
query = """
SELECT payer_type,
       MIN(claim_amount_usd) AS Lowest_Claim
FROM claims
GROUP BY payer_type
ORDER BY Lowest_Claim;
"""

pd.read_sql(query, conn)

           payer_type  Lowest_Claim
0    Medicaid_Managed         52.24
1        Medicare_FFS         63.25
2  Medicare_Advantage         66.03
3      Commercial_HMO         73.76
4      Commercial_EPO         78.46
5      Commercial_PPO         80.98

In [42]:
#Denial Rate by Payer
query = """
SELECT payer_type,
       COUNT(CASE WHEN outcome='denied' THEN 1 END) AS Denied_Claims,
       COUNT(*) AS Total_Claims,
       ROUND(
           COUNT(CASE WHEN outcome='denied' THEN 1 END) * 100.0 / COUNT(*),
           2
       ) AS Denial_Rate
FROM claims
GROUP BY payer_type
ORDER BY Denial_Rate DESC;
"""

pd.read_sql(query, conn)

           payer_type  Denied_Claims  Total_Claims  Denial_Rate
0    Medicaid_Managed           5130         17996        28.51
1  Medicare_Advantage           6148         21758        28.26
2        Medicare_FFS           7378         26300        28.05
3      Commercial_HMO           4324         15458        27.97
4      Commercial_PPO           8338         30016        27.78
5      Commercial_EPO           2346          8472        27.69

In [43]:
# payer rate by payer
query = """
SELECT payer_type,
       ROUND(
           COUNT(CASE WHEN outcome='paid' THEN 1 END) * 100.0 / COUNT(*),
           2
       ) AS Paid_Rate
FROM claims
GROUP BY payer_type
ORDER BY Paid_Rate DESC;
"""

pd.read_sql(query, conn)

           payer_type  Paid_Rate
0      Commercial_PPO      52.14
1  Medicare_Advantage      52.10
2      Commercial_EPO      51.99
3      Commercial_HMO      51.95
4        Medicare_FFS      51.93
5    Medicaid_Managed      51.68

In [44]:
#pending rate by payer
query = """
SELECT payer_type,
       ROUND(
           COUNT(CASE WHEN outcome='pending' THEN 1 END) * 100.0 / COUNT(*),
           2
       ) AS Pending_Rate
FROM claims
GROUP BY payer_type
ORDER BY Pending_Rate DESC;
"""

pd.read_sql(query, conn)

           payer_type  Pending_Rate
0    Medicaid_Managed          7.26
1      Commercial_PPO          7.17
2  Medicare_Advantage          7.11
3      Commercial_EPO          7.07
4      Commercial_HMO          7.03
5        Medicare_FFS          6.84

In [45]:
#Prior Authorization Required by Payer
query = """
SELECT payer_type,
       COUNT(*) AS Prior_Auth_Required
FROM claims
WHERE prior_auth_required=1
GROUP BY payer_type
ORDER BY Prior_Auth_Required DESC;
"""

pd.read_sql(query, conn)

           payer_type  Prior_Auth_Required
0  Medicare_Advantage                21758
1      Commercial_HMO                15458
2      Commercial_PPO                 6181
3        Medicare_FFS                 5385
4    Medicaid_Managed                 3686
5      Commercial_EPO                 1704

In [46]:
#prior Authorization Obtained by payer
query = """
SELECT payer_type,
       COUNT(*) AS Prior_Auth_Obtained
FROM claims
WHERE prior_auth_obtained=1
GROUP BY payer_type
ORDER BY Prior_Auth_Obtained DESC;
"""

pd.read_sql(query, conn)

           payer_type  Prior_Auth_Obtained
0  Medicare_Advantage                18755
1      Commercial_HMO                13336
2      Commercial_PPO                 5325
3        Medicare_FFS                 4624
4    Medicaid_Managed                 3174
5      Commercial_EPO                 1466

DENIAL ANALYSIS

In [47]:
# Total denied claim
query = """
SELECT COUNT(*) AS Total_Denied_Claims
FROM claims
WHERE outcome = 'denied';
"""

pd.read_sql(query, conn)

   Total_Denied_Claims
0                33664

In [48]:
# Total Denial code
query = """
SELECT denial_reason_code,
       COUNT(*) AS Total_Denials
FROM claims
WHERE outcome='denied'
GROUP BY denial_reason_code
ORDER BY Total_Denials DESC;
"""

pd.read_sql(query, conn)

   denial_reason_code  Total_Denials
0               CO-11           4236
1               CO-16           3928
2              CO-109           3654
3               CO-97           3214
4                CO-4           2354
5              CO-119           2354
6               CO-50           2341
7               CO-29           2315
8              PR-204           2065
9               N-130           2043
10              PR-27           1429
11              CO-22           1331
12              OA-18            900
13              CO-18            889
14              OA-23            611

In [49]:
# top denial Categories
query = """
SELECT denial_category,
       COUNT(*) AS Total_Denials
FROM claims
WHERE outcome='denied'
GROUP BY denial_category
ORDER BY Total_Denials DESC;
"""

pd.read_sql(query, conn)

     denial_category  Total_Denials
0  medical_necessity           9444
1       coding_error           7344
2       auth_missing           6140
3        eligibility           4084
4          duplicate           2645
5      timely_filing           2315
6           bundling           1692

In [50]:
#Revenue Lost by Denial Code
query = """
SELECT denial_reason_code,
       ROUND(SUM(claim_amount_usd),2) AS Lost_Revenue
FROM claims
WHERE outcome='denied'
GROUP BY denial_reason_code
ORDER BY Lost_Revenue DESC;
"""

pd.read_sql(query, conn)

   denial_reason_code  Lost_Revenue
0               CO-11  9,705,541.99
1               CO-16  8,633,921.26
2              CO-109  8,440,773.79
3               CO-97  7,038,820.50
4                CO-4  5,190,226.36
5               CO-50  5,096,456.23
6              CO-119  4,929,592.21
7               N-130  4,848,941.29
8               CO-29  4,823,524.07
9              PR-204  4,221,657.78
10              PR-27  3,112,400.74
11              CO-22  2,820,929.11
12              CO-18  2,059,308.88
13              OA-18  1,845,885.77
14              OA-23  1,364,388.09

In [51]:
#Average claim amount by Denial code
query = """
SELECT denial_reason_code,
       ROUND(AVG(claim_amount_usd),2) AS Avg_Claim_Amount
FROM claims
WHERE outcome='denied'
GROUP BY denial_reason_code
ORDER BY Avg_Claim_Amount DESC;
"""

pd.read_sql(query, conn)

   denial_reason_code  Avg_Claim_Amount
0               N-130          2,373.44
1               CO-18          2,316.43
2              CO-109          2,310.01
3               CO-11          2,291.20
4               OA-23          2,233.04
5                CO-4          2,204.85
6               CO-16          2,198.05
7               CO-97          2,190.05
8               PR-27          2,178.03
9               CO-50          2,177.04
10              CO-22          2,119.41
11             CO-119          2,094.13
12              CO-29          2,083.60
13              OA-18          2,050.98
14             PR-204          2,044.39

In [52]:
# Denial by payer
query = """
SELECT payer_type,
       COUNT(*) AS Denied_Claims
FROM claims
WHERE outcome='denied'
GROUP BY payer_type
ORDER BY Denied_Claims DESC;
"""

pd.read_sql(query, conn)

           payer_type  Denied_Claims
0      Commercial_PPO           8338
1        Medicare_FFS           7378
2  Medicare_Advantage           6148
3    Medicaid_Managed           5130
4      Commercial_HMO           4324
5      Commercial_EPO           2346

In [53]:
#Denials by Provider Specialty
query = """
SELECT provider_specialty,
       COUNT(*) AS Denied_Claims
FROM claims
WHERE outcome='denied'
GROUP BY provider_specialty
ORDER BY Denied_Claims DESC;
"""

pd.read_sql(query, conn)

       provider_specialty  Denied_Claims
0      Emergency_Medicine           4695
1       Internal_Medicine           3997
2              Cardiology           3365
3      Orthopedic_Surgery           2940
4       Behavioral_Health           2615
5                Oncology           2410
6               Radiology           2350
7        Gastroenterology           2094
8            Primary_Care           2075
9               Neurology           1998
10            Pulmonology           1733
11  Obstetrics_Gynecology           1698
12       Physical_Therapy           1694

In [54]:
#Denied by CPT code
query = """
SELECT cpt_code,
       COUNT(*) AS Denied_Claims
FROM claims
WHERE outcome='denied'
GROUP BY cpt_code
ORDER BY Denied_Claims DESC;
"""

pd.read_sql(query, conn)

   cpt_code  Denied_Claims
0     99214           4689
1     99213           3281
2     99215           2154
3     99283           1409
4     99284           1387
5     99285            972
6     90834            794
7     90837            772
8     96413            735
9     93454            694
10    93280            680
11    93306            663
12    93000            660
13    45378            651
14    20610            604
15    27447            597
16    29881            592
17    29827            566
18    59400            523
19    90791            522
20    97110            506
21    97530            492
22    99291            491
23    70553            490
24    77301            489
25    71046            485
26    74177            480
27    78452            459
28    72148            436
29    99396            421
30    43235            403
31    43239            402
32    95819            397
33    64483            394
34    99233            387
35    99232            376
36    38220            375
37    76805            362
38    97140            347
39    31623            343
40    94726            337
41    94010            329
42    58150            320
43    H0001            255
44    45380            207
45    99391            203
46    97012            195
47    95886            184
48    97035            154

In [55]:
#Denied by ICD Diagnosis
query = """
SELECT primary_icd10_dx,
       COUNT(*) AS Denied_Claims
FROM claims
WHERE outcome='denied'
GROUP BY primary_icd10_dx
ORDER BY Denied_Claims DESC;
"""

pd.read_sql(query, conn)

   primary_icd10_dx  Denied_Claims
0               I10           2419
1             E11.9           2125
2             M54.5           1823
3             F41.1           1503
4            M17.11           1493
5             F32.1           1462
6            I25.10           1437
7             E78.5           1436
8             J18.9           1174
9           G43.909           1167
10            J06.9           1118
11           I48.91           1118
12          M25.511           1111
13            K21.0           1095
14            I50.9           1093
15            J44.1           1092
16            E66.9           1045
17          C50.911            765
18           Z34.00            760
19          S72.001            755
20            A41.9            753
21              G35            742
22           F10.20            740
23           K57.30            739
24           C34.10            739
25              O80            734
26            F20.9            720
27            C18.9            720
28           G89.29            707
29           J45.41            697
30            K92.1            382

In [56]:
#Denied nu Quarter
query = """
SELECT claim_quarter,
       COUNT(*) AS Denied_Claims
FROM claims
WHERE outcome='denied'
GROUP BY claim_quarter
ORDER BY Denied_Claims DESC;
"""

pd.read_sql(query, conn)

  claim_quarter  Denied_Claims
0            Q2           9565
1            Q1           9522
2            Q3           7310
3            Q4           7267

In [57]:
#Denials Due to Missing Prior Authorization
query = """
SELECT COUNT(*) AS Missing_Prior_Auth_Denials
FROM claims
WHERE outcome='denied'
AND prior_auth_required=1
AND prior_auth_obtained=0;
"""

pd.read_sql(query, conn)

   Missing_Prior_Auth_Denials
0                        5310

In [58]:
#Top 5 Denial Codes with Their Categories
query = """
SELECT denial_reason_code,
       denial_category,
       COUNT(*) AS Total_Denials
FROM claims
WHERE outcome='denied'
GROUP BY denial_reason_code, denial_category
ORDER BY Total_Denials DESC
LIMIT 5;
"""

pd.read_sql(query, conn)

  denial_reason_code    denial_category  Total_Denials
0              CO-11  medical_necessity           2419
1             CO-119  medical_necessity           2354
2              CO-50  medical_necessity           2341
3             CO-109  medical_necessity           2330
4              CO-29      timely_filing           2315

CPT ANALYSIS

In [59]:
#Most Frequently Billed CPT Codes
query = """
SELECT cpt_code,
       COUNT(*) AS Total_Claims
FROM claims
GROUP BY cpt_code
ORDER BY Total_Claims DESC;
"""

pd.read_sql(query, conn)

   cpt_code  Total_Claims
0     99214         16819
1     99213         11509
2     99215          7515
3     99284          4992
4     99283          4971
5     99285          3394
6     90834          2816
7     90837          2809
8     96413          2575
9     93454          2456
10    93306          2442
11    93000          2384
12    93280          2354
13    45378          2267
14    27447          2215
15    20610          2157
16    29827          2150
17    29881          2069
18    90791          1893
19    97530          1820
20    59400          1810
21    97110          1765
22    99291          1750
23    70553          1737
24    71046          1725
25    77301          1693
26    74177          1693
27    78452          1686
28    72148          1630
29    99396          1494
30    43235          1483
31    99232          1463
32    43239          1456
33    64483          1433
34    95819          1426
35    99233          1395
36    38220          1261
37    31623          1236
38    97140          1231
39    76805          1208
40    94726          1204
41    94010          1180
42    58150          1160
43    H0001           926
44    99391           714
45    45380           711
46    95886           701
47    97012           636
48    97035           586

In [61]:
#Top Revenue-Generating CPT Codes
query = """
SELECT cpt_code,
       ROUND(SUM(claim_amount_usd),2) AS Total_Revenue
FROM claims
GROUP BY cpt_code
ORDER BY Total_Revenue DESC;
"""

pd.read_sql(query, conn)

   cpt_code  Total_Revenue
0     27447  52,837,037.27
1     93454  27,234,339.78
2     59400  18,482,605.09
3     29827  18,464,652.62
4     29881  14,152,367.17
5     93280  11,082,127.08
6     58150  10,308,668.68
7     77301   8,273,269.51
8     96413   6,955,648.85
9     45378   6,898,242.68
10    93306   6,192,023.78
11    99285   6,082,648.72
12    31623   6,056,179.13
13    43239   5,861,558.09
14    99284   5,715,775.49
15    99291   5,590,913.36
16    43235   5,078,814.17
17    99214   4,809,961.87
18    78452   4,647,894.69
19    38220   4,567,467.58
20    70553   4,504,199.89
21    64483   4,261,523.71
22    99283   3,806,032.93
23    74177   3,329,492.15
24    99215   2,880,709.03
25    72148   2,794,971.37
26    45380   2,681,472.68
27    95819   2,427,278.71
28    99213   2,305,461.27
29    71046     950,775.92
30    95886     791,027.71
31    90837     695,818.38
32    20610     649,202.62
33    90791     647,834.19
34    76805     569,013.30
35    93000     560,369.21
36    90834     553,721.39
37    99233     458,367.48
38    99396     379,703.40
39    99232     347,555.82
40    94726     337,402.60
41    97530     308,700.71
42    97110     269,569.70
43    H0001     257,818.92
44    94010     250,602.18
45    97140     201,405.17
46    99391     162,310.21
47    97035      77,775.32
48    97012      77,450.61

In [62]:
#Average Claim Amount by CPT Code
query = """
SELECT cpt_code,
       ROUND(AVG(claim_amount_usd),2) AS Avg_Claim_Amount
FROM claims
GROUP BY cpt_code
ORDER BY Avg_Claim_Amount DESC;
"""

pd.read_sql(query, conn)

   cpt_code  Avg_Claim_Amount
0     27447         23,854.19
1     93454         11,088.90
2     59400         10,211.38
3     58150          8,886.78
4     29827          8,588.21
5     29881          6,840.20
6     31623          4,899.82
7     77301          4,886.75
8     93280          4,707.79
9     43239          4,025.80
10    45380          3,771.41
11    38220          3,622.10
12    43235          3,424.69
13    99291          3,194.81
14    45378          3,042.89
15    64483          2,973.85
16    78452          2,756.76
17    96413          2,701.22
18    70553          2,593.09
19    93306          2,535.64
20    74177          1,966.62
21    99285          1,792.18
22    72148          1,714.71
23    95819          1,702.16
24    99284          1,144.99
25    95886          1,128.43
26    99283            765.65
27    71046            551.17
28    76805            471.04
29    99215            383.33
30    90791            342.23
31    99233            328.58
32    20610            300.97
33    99214            285.98
34    94726            280.23
35    H0001            278.42
36    99396            254.15
37    90837            247.71
38    99232            237.56
39    93000            235.05
40    99391            227.33
41    94010            212.37
42    99213            200.32
43    90834            196.63
44    97530            169.62
45    97140            163.61
46    97110            152.73
47    97035            132.72
48    97012            121.78

In [63]:
#Highest Individual Claim by CPT Code
query = """
SELECT cpt_code,
       MAX(claim_amount_usd) AS Highest_Claim
FROM claims
GROUP BY cpt_code
ORDER BY Highest_Claim DESC;
"""

pd.read_sql(query, conn)

   cpt_code  Highest_Claim
0     27447      37,918.58
1     93454      17,993.24
2     59400      15,989.34
3     29827      13,991.75
4     58150      13,933.82
5     29881      10,950.17
6     31623       7,993.62
7     77301       7,990.24
8     93280       7,497.65
9     43239       6,496.32
10    38220       5,995.26
11    45380       5,978.84
12    43235       5,498.16
13    99291       4,999.76
14    45378       4,992.98
15    64483       4,979.83
16    96413       4,499.77
17    78452       4,483.94
18    93306       4,199.73
19    70553       4,194.37
20    74177       3,192.14
21    99285       2,798.62
22    72148       2,792.54
23    95819       2,777.19
24    99284       1,799.82
25    95886       1,794.88
26    99283       1,199.89
27    71046         899.05
28    76805         747.59
29    99215         599.94
30    90791         549.62
31    99233         519.70
32    20610         499.44
33    99214         449.87
34    H0001         448.90
35    94726         448.42
36    99396         399.43
37    90837         380.00
38    99232         379.42
39    93000         378.75
40    94010         349.88
41    99391         349.76
42    99213         319.97
43    90834         299.91
44    97530         279.34
45    97140         269.73
46    97110         259.13
47    97035         219.84
48    97012         199.92

In [64]:
#Lowest Individual Claim by CPT Code
query = """
SELECT cpt_code,
       MIN(claim_amount_usd) AS Lowest_Claim
FROM claims
GROUP BY cpt_code
ORDER BY Lowest_Claim;
"""

pd.read_sql(query, conn)

   cpt_code  Lowest_Claim
0     97012         52.24
1     97035         58.58
2     97110         65.45
3     97140         71.96
4     97530         78.38
5     99213         97.51
6     94010         97.71
7     90834        104.22
8     93000        117.39
9     99232        117.48
10    99391        120.38
11    90837        130.01
12    H0001        130.41
13    99396        130.44
14    20610        130.59
15    94726        132.71
16    99214        143.01
17    90791        162.71
18    99233        165.07
19    99215        195.04
20    76805        229.45
21    71046        260.46
22    99283        390.92
23    95886        524.13
24    99284        586.35
25    72148        780.97
26    95819        784.62
27    74177        910.08
28    99285        912.33
29    93306      1,170.83
30    70553      1,172.18
31    96413      1,173.15
32    78452      1,301.62
33    64483      1,302.14
34    45378      1,437.52
35    99291      1,626.61
36    43235      1,626.79
37    38220      1,627.89
38    45380      1,940.92
39    43239      1,967.88
40    93280      2,283.37
41    77301      2,287.06
42    31623      2,305.32
43    29881      3,297.04
44    29827      3,909.07
45    58150      4,605.92
46    93454      5,219.81
47    59400      5,221.23
48    27447     11,739.23

In [65]:
#Denied Claims by CPT Code
query = """
SELECT cpt_code,
       COUNT(*) AS Denied_Claims
FROM claims
WHERE outcome='denied'
GROUP BY cpt_code
ORDER BY Denied_Claims DESC;
"""

pd.read_sql(query, conn)

   cpt_code  Denied_Claims
0     99214           4689
1     99213           3281
2     99215           2154
3     99283           1409
4     99284           1387
5     99285            972
6     90834            794
7     90837            772
8     96413            735
9     93454            694
10    93280            680
11    93306            663
12    93000            660
13    45378            651
14    20610            604
15    27447            597
16    29881            592
17    29827            566
18    59400            523
19    90791            522
20    97110            506
21    97530            492
22    99291            491
23    70553            490
24    77301            489
25    71046            485
26    74177            480
27    78452            459
28    72148            436
29    99396            421
30    43235            403
31    43239            402
32    95819            397
33    64483            394
34    99233            387
35    99232            376
36    38220            375
37    76805            362
38    97140            347
39    31623            343
40    94726            337
41    94010            329
42    58150            320
43    H0001            255
44    45380            207
45    99391            203
46    97012            195
47    95886            184
48    97035            154

In [66]:
#Revenue Lost Due to Denials by CPT Code
query = """
SELECT cpt_code,
       ROUND(SUM(claim_amount_usd),2) AS Lost_Revenue
FROM claims
WHERE outcome='denied'
GROUP BY cpt_code
ORDER BY Lost_Revenue DESC;
"""

pd.read_sql(query, conn)

   cpt_code  Lost_Revenue
0     27447 14,148,749.66
1     93454  7,664,225.20
2     59400  5,337,627.81
3     29827  4,947,979.15
4     29881  3,994,922.63
5     93280  3,168,889.58
6     58150  2,815,705.06
7     77301  2,365,675.14
8     45378  1,994,269.94
9     96413  1,959,857.56
10    99285  1,731,983.64
11    93306  1,696,666.72
12    31623  1,660,607.80
13    43239  1,630,322.90
14    99284  1,572,592.62
15    99291  1,548,395.69
16    43235  1,375,114.48
17    38220  1,354,160.19
18    99214  1,337,590.81
19    70553  1,278,195.18
20    78452  1,268,417.98
21    64483  1,207,264.56
22    99283  1,068,805.64
23    74177    947,830.67
24    99215    819,543.11
25    45380    774,315.29
26    72148    760,200.87
27    95819    671,523.82
28    99213    656,699.30
29    71046    266,190.87
30    95886    203,131.52
31    90837    191,474.03
32    20610    181,859.31
33    90791    181,546.61
34    76805    171,377.93
35    93000    156,861.65
36    90834    155,563.45
37    99233    126,703.88
38    99396    106,313.26
39    94726     94,238.91
40    99232     88,635.64
41    97530     84,759.16
42    97110     76,463.00
43    H0001     72,232.20
44    94010     69,664.11
45    97140     56,309.68
46    99391     46,668.80
47    97012     23,605.41
48    97035     20,635.65

In [67]:
#Denial Rate by CPT Code
query = """
SELECT cpt_code,
       COUNT(CASE WHEN outcome='denied' THEN 1 END) AS Denied_Claims,
       COUNT(*) AS Total_Claims,
       ROUND(
           COUNT(CASE WHEN outcome='denied' THEN 1 END) * 100.0 / COUNT(*),
           2
       ) AS Denial_Rate
FROM claims
GROUP BY cpt_code
ORDER BY Denial_Rate DESC;
"""

pd.read_sql(query, conn)

   cpt_code  Denied_Claims  Total_Claims  Denial_Rate
0     97012            195           636        30.66
1     76805            362          1208        29.97
2     38220            375          1261        29.74
3     45380            207           711        29.11
4     59400            523          1810        28.90
5     93280            680          2354        28.89
6     77301            489          1693        28.88
7     45378            651          2267        28.72
8     97110            506          1765        28.67
9     99215           2154          7515        28.66
10    99285            972          3394        28.64
11    29881            592          2069        28.61
12    96413            735          2575        28.54
13    99213           3281         11509        28.51
14    99391            203           714        28.43
15    74177            480          1693        28.35
16    99283           1409          4971        28.34
17    93454            694          2456        28.26
18    70553            490          1737        28.21
19    90834            794          2816        28.20
20    97140            347          1231        28.19
21    99396            421          1494        28.18
22    71046            485          1725        28.12
23    99291            491          1750        28.06
24    20610            604          2157        28.00
25    94726            337          1204        27.99
26    99214           4689         16819        27.88
27    94010            329          1180        27.88
28    95819            397          1426        27.84
29    99284           1387          4992        27.78
30    31623            343          1236        27.75
31    99233            387          1395        27.74
32    93000            660          2384        27.68
33    43239            402          1456        27.61
34    58150            320          1160        27.59
35    90791            522          1893        27.58
36    H0001            255           926        27.54
37    64483            394          1433        27.49
38    90837            772          2809        27.48
39    78452            459          1686        27.22
40    43235            403          1483        27.17
41    93306            663          2442        27.15
42    97530            492          1820        27.03
43    27447            597          2215        26.95
44    72148            436          1630        26.75
45    29827            566          2150        26.33
46    97035            154           586        26.28
47    95886            184           701        26.25
48    99232            376          1463        25.70

In [68]:
#Paid Claims by CPT Code
query = """
SELECT cpt_code,
       COUNT(*) AS Paid_Claims
FROM claims
WHERE outcome='paid'
GROUP BY cpt_code
ORDER BY Paid_Claims DESC;
"""

pd.read_sql(query, conn)

   cpt_code  Paid_Claims
0     99214         8899
1     99213         5983
2     99215         3778
3     99283         2598
4     99284         2596
5     99285         1746
6     90834         1456
7     90837         1445
8     96413         1367
9     93454         1283
10    93306         1270
11    93000         1241
12    93280         1199
13    45378         1183
14    27447         1158
15    29827         1123
16    20610         1120
17    29881         1064
18    90791          980
19    97530          951
20    59400          936
21    99291          915
22    78452          909
23    71046          900
24    70553          899
25    97110          885
26    72148          870
27    77301          853
28    74177          850
29    99232          812
30    43235          772
31    43239          771
32    99396          767
33    64483          758
34    99233          723
35    95819          720
36    31623          649
37    38220          642
38    97140          634
39    94726          632
40    94010          615
41    58150          594
42    76805          588
43    H0001          492
44    95886          375
45    99391          373
46    45380          373
47    97035          323
48    97012          309

In [69]:
#Pending Claims by CPT Code
query = """
SELECT cpt_code,
       COUNT(*) AS Pending_Claims
FROM claims
WHERE outcome='pending'
GROUP BY cpt_code
ORDER BY Pending_Claims DESC;
"""

pd.read_sql(query, conn)

   cpt_code  Pending_Claims
0     99214            1191
1     99213             806
2     99215             582
3     99284             372
4     99283             346
5     99285             234
6     90837             209
7     90834             191
8     96413             182
9     93306             175
10    93280             171
11    93000             168
12    93454             166
13    45378             162
14    27447             154
15    29827             153
16    29881             151
17    20610             151
18    97530             136
19    77301             135
20    97110             131
21    74177             131
22    99291             127
23    90791             123
24    59400             122
25    95819             120
26    70553             120
27    43235             113
28    78452             110
29    71046             108
30    99232             105
31    72148             105
32    99233              99
33    64483              99
34    99396              95
35    97140              94
36    31623              89
37    76805              87
38    43239              82
39    94010              79
40    38220              78
41    94726              77
42    58150              76
43    H0001              63
44    95886              55
45    99391              48
46    45380              43
47    97035              39
48    97012              35

ICD ANALYSIS

In [70]:
#Most Common Diagnoses
query = """
SELECT primary_icd10_dx,
       COUNT(*) AS Total_Claims
FROM claims
GROUP BY primary_icd10_dx
ORDER BY Total_Claims DESC;
"""

pd.read_sql(query, conn)

   primary_icd10_dx  Total_Claims
0               I10          8996
1             E11.9          7773
2             M54.5          6251
3            M17.11          5280
4             F32.1          5220
5            I25.10          5208
6             F41.1          5195
7             E78.5          5182
8             J18.9          3992
9           G43.909          3991
10           I48.91          3974
11            K21.0          3957
12            J06.9          3934
13          M25.511          3930
14            I50.9          3887
15            E66.9          3867
16            J44.1          3856
17           C34.10          2704
18            F20.9          2695
19              G35          2679
20          S72.001          2669
21           G89.29          2660
22          C50.911          2657
23           K57.30          2648
24           J45.41          2620
25           F10.20          2603
26            C18.9          2581
27              O80          2577
28           Z34.00          2576
29            A41.9          2552
30            K92.1          1286

In [71]:
#Revenue by Diagnosis
query = """
SELECT primary_icd10_dx,
       ROUND(SUM(claim_amount_usd),2) AS Total_Revenue
FROM claims
GROUP BY primary_icd10_dx
ORDER BY Total_Revenue DESC;
"""

pd.read_sql(query, conn)

   primary_icd10_dx  Total_Revenue
0               I10  19,370,032.74
1             E11.9  17,541,138.57
2             M54.5  13,846,062.96
3            M17.11  12,317,922.30
4             F41.1  11,766,477.09
5             E78.5  11,473,377.65
6             F32.1  11,163,099.41
7            I25.10  10,912,645.20
8             K21.0   8,979,584.93
9            I48.91   8,941,299.81
10          G43.909   8,928,490.25
11          M25.511   8,920,865.70
12            I50.9   8,850,784.71
13            J44.1   8,843,308.31
14            J18.9   8,804,899.04
15            J06.9   8,741,789.74
16            E66.9   8,228,894.73
17           C34.10   6,282,966.30
18           G89.29   6,067,256.57
19              O80   6,025,752.74
20          S72.001   5,911,033.97
21            A41.9   5,910,943.12
22            F20.9   5,883,544.50
23              G35   5,862,525.91
24          C50.911   5,764,302.11
25           J45.41   5,728,547.00
26           Z34.00   5,704,563.26
27            C18.9   5,688,206.81
28           K57.30   5,633,849.31
29           F10.20   5,608,694.54
30            K92.1   3,126,902.91

In [72]:
#Average Claim Amount by Diagnosis
query = """
SELECT primary_icd10_dx,
       ROUND(AVG(claim_amount_usd),2) AS Avg_Claim
FROM claims
GROUP BY primary_icd10_dx
ORDER BY Avg_Claim DESC;
"""

pd.read_sql(query, conn)

   primary_icd10_dx  Avg_Claim
0             K92.1   2,431.50
1               O80   2,338.28
2            M17.11   2,332.94
3            C34.10   2,323.58
4             A41.9   2,316.20
5             J44.1   2,293.39
6            G89.29   2,280.92
7             I50.9   2,277.02
8           M25.511   2,269.94
9             K21.0   2,269.29
10            F41.1   2,264.96
11            E11.9   2,256.68
12           I48.91   2,249.95
13          G43.909   2,237.16
14            J06.9   2,222.11
15            M54.5   2,215.02
16          S72.001   2,214.70
17           Z34.00   2,214.50
18            E78.5   2,214.08
19            J18.9   2,205.64
20            C18.9   2,203.88
21              G35   2,188.33
22           J45.41   2,186.47
23            F20.9   2,183.13
24          C50.911   2,169.48
25           F10.20   2,154.70
26              I10   2,153.18
27            F32.1   2,138.52
28            E66.9   2,127.98
29           K57.30   2,127.59
30           I25.10   2,095.36

In [73]:
#Highest Claim Amount by Diagnosis
query = """
SELECT primary_icd10_dx,
       MAX(claim_amount_usd) AS Highest_Claim
FROM claims
GROUP BY primary_icd10_dx
ORDER BY Highest_Claim DESC;
"""

pd.read_sql(query, conn)

   primary_icd10_dx  Highest_Claim
0            J45.41      37,918.58
1             M54.5      37,897.59
2           M25.511      37,883.35
3             J06.9      37,803.07
4            I25.10      37,796.11
5            M17.11      37,784.16
6             F32.1      37,632.91
7            I48.91      37,543.20
8             F41.1      37,481.36
9             K21.0      37,480.07
10          S72.001      37,444.00
11          C50.911      37,428.73
12            E66.9      37,389.25
13          G43.909      37,338.48
14            J44.1      37,192.49
15              G35      37,081.28
16            E78.5      37,056.53
17            J18.9      36,989.70
18              O80      36,967.66
19            A41.9      36,853.28
20            I50.9      36,588.39
21            F20.9      36,404.48
22           Z34.00      36,237.04
23              I10      36,190.32
24            E11.9      35,952.81
25           F10.20      35,230.90
26           G89.29      34,865.85
27            C18.9      33,719.88
28           C34.10      33,112.60
29           K57.30      32,573.49
30            K92.1      30,964.63

In [74]:
#Lowest Claim Amount by Diagnosis
query = """
SELECT primary_icd10_dx,
       MIN(claim_amount_usd) AS Lowest_Claim
FROM claims
GROUP BY primary_icd10_dx
ORDER BY Lowest_Claim;
"""

pd.read_sql(query, conn)

   primary_icd10_dx  Lowest_Claim
0            I48.91         52.24
1           S72.001         52.80
2             I50.9         53.78
3             J18.9         53.83
4             J44.1         54.24
5            G89.29         54.75
6           G43.909         55.50
7               O80         57.12
8             M54.5         58.29
9             E78.5         58.58
10            A41.9         61.19
11          C50.911         62.18
12            E66.9         63.25
13           I25.10         64.31
14          M25.511         65.31
15            F41.1         65.38
16            E11.9         65.45
17            F20.9         65.52
18            J06.9         65.59
19            F32.1         66.03
20              I10         66.47
21           C34.10         66.50
22           M17.11         66.58
23           F10.20         67.35
24            C18.9         70.33
25           Z34.00         73.29
26           K57.30         74.57
27            K21.0         74.95
28              G35         75.61
29           J45.41         75.68
30            K92.1         79.35

In [75]:
#Denied Claims by Diagnosis
query = """
SELECT primary_icd10_dx,
       COUNT(*) AS Denied_Claims
FROM claims
WHERE outcome='denied'
GROUP BY primary_icd10_dx
ORDER BY Denied_Claims DESC;
"""

pd.read_sql(query, conn)

   primary_icd10_dx  Denied_Claims
0               I10           2419
1             E11.9           2125
2             M54.5           1823
3             F41.1           1503
4            M17.11           1493
5             F32.1           1462
6            I25.10           1437
7             E78.5           1436
8             J18.9           1174
9           G43.909           1167
10            J06.9           1118
11           I48.91           1118
12          M25.511           1111
13            K21.0           1095
14            I50.9           1093
15            J44.1           1092
16            E66.9           1045
17          C50.911            765
18           Z34.00            760
19          S72.001            755
20            A41.9            753
21              G35            742
22           F10.20            740
23           K57.30            739
24           C34.10            739
25              O80            734
26            F20.9            720
27            C18.9            720
28           G89.29            707
29           J45.41            697
30            K92.1            382

In [76]:
#Revenue Lost by Diagnosis
query = """
SELECT primary_icd10_dx,
       ROUND(SUM(claim_amount_usd),2) AS Lost_Revenue
FROM claims
WHERE outcome='denied'
GROUP BY primary_icd10_dx
ORDER BY Lost_Revenue DESC;
"""

pd.read_sql(query, conn)

   primary_icd10_dx  Lost_Revenue
0               I10  5,580,154.78
1             E11.9  4,588,914.02
2             M54.5  3,812,685.49
3            M17.11  3,512,353.33
4             F41.1  3,371,195.65
5             E78.5  3,161,683.77
6             F32.1  3,097,960.36
7            I25.10  2,950,164.09
8             J18.9  2,876,335.68
9           G43.909  2,602,238.25
10          M25.511  2,597,996.95
11           I48.91  2,497,267.29
12            J44.1  2,438,599.00
13            K21.0  2,424,365.86
14            I50.9  2,276,614.24
15            J06.9  2,234,660.79
16            E66.9  2,104,658.07
17          C50.911  1,807,773.06
18           C34.10  1,781,063.38
19           Z34.00  1,757,758.24
20            A41.9  1,742,414.11
21              O80  1,641,514.86
22          S72.001  1,624,250.25
23           K57.30  1,617,680.57
24           G89.29  1,603,239.35
25              G35  1,541,954.30
26            F20.9  1,525,686.74
27           J45.41  1,506,713.67
28           F10.20  1,499,312.87
29            C18.9  1,469,915.05
30            K92.1    885,244.00

In [77]:
#Denial Rate by Diagnosis
query = """
SELECT primary_icd10_dx,
       COUNT(CASE WHEN outcome='denied' THEN 1 END) AS Denied_Claims,
       COUNT(*) AS Total_Claims,
       ROUND(
           COUNT(CASE WHEN outcome='denied' THEN 1 END) * 100.0 / COUNT(*),
           2
       ) AS Denial_Rate
FROM claims
GROUP BY primary_icd10_dx
ORDER BY Denial_Rate DESC;
"""

pd.read_sql(query, conn)

   primary_icd10_dx  Denied_Claims  Total_Claims  Denial_Rate
0             K92.1            382          1286        29.70
1             A41.9            753          2552        29.51
2            Z34.00            760          2576        29.50
3             J18.9           1174          3992        29.41
4           G43.909           1167          3991        29.24
5             M54.5           1823          6251        29.16
6             F41.1           1503          5195        28.93
7           C50.911            765          2657        28.79
8               O80            734          2577        28.48
9            F10.20            740          2603        28.43
10            J06.9           1118          3934        28.42
11            J44.1           1092          3856        28.32
12          S72.001            755          2669        28.29
13           M17.11           1493          5280        28.28
14          M25.511           1111          3930        28.27
15           I48.91           1118          3974        28.13
16            I50.9           1093          3887        28.12
17            F32.1           1462          5220        28.01
18           K57.30            739          2648        27.91
19            C18.9            720          2581        27.90
20            E78.5           1436          5182        27.71
21              G35            742          2679        27.70
22            K21.0           1095          3957        27.67
23           I25.10           1437          5208        27.59
24            E11.9           2125          7773        27.34
25           C34.10            739          2704        27.33
26            E66.9           1045          3867        27.02
27              I10           2419          8996        26.89
28            F20.9            720          2695        26.72
29           J45.41            697          2620        26.60
30           G89.29            707          2660        26.58

In [78]:
#Paid Claims by Diagnosis
query = """
SELECT primary_icd10_dx,
       COUNT(*) AS Paid_Claims
FROM claims
WHERE outcome='paid'
GROUP BY primary_icd10_dx
ORDER BY Paid_Claims DESC;
"""

pd.read_sql(query, conn)

   primary_icd10_dx  Paid_Claims
0               I10         4849
1             E11.9         4120
2             M54.5         3158
3            M17.11         2785
4             F32.1         2710
5            I25.10         2689
6             E78.5         2674
7             F41.1         2635
8             E66.9         2080
9             J06.9         2075
10            K21.0         2064
11           I48.91         2049
12            J18.9         2038
13          G43.909         2029
14            I50.9         2019
15          M25.511         2005
16            J44.1         1980
17           C34.10         1434
18            F20.9         1426
19           J45.41         1417
20           G89.29         1410
21           K57.30         1384
22          S72.001         1369
23            C18.9         1356
24              G35         1352
25          C50.911         1351
26              O80         1340
27           Z34.00         1327
28           F10.20         1317
29            A41.9         1270
30            K92.1          667

In [79]:
#Pending Claims by Diagnosis
query = """
SELECT primary_icd10_dx,
       COUNT(*) AS Pending_Claims
FROM claims
WHERE outcome='pending'
GROUP BY primary_icd10_dx
ORDER BY Pending_Claims DESC;
"""

pd.read_sql(query, conn)

   primary_icd10_dx  Pending_Claims
0               I10             628
1             E11.9             565
2             M54.5             449
3            I25.10             398
4             E78.5             377
5            M17.11             360
6             F32.1             360
7             F41.1             355
8           M25.511             291
9             J44.1             281
10            I50.9             277
11          G43.909             275
12           I48.91             271
13            E66.9             269
14            J06.9             266
15            J18.9             262
16            K21.0             259
17              G35             219
18            F20.9             210
19            A41.9             204
20           C34.10             194
21           K57.30             192
22          C50.911             192
23           G89.29             190
24           J45.41             185
25           F10.20             183
26            C18.9             177
27           Z34.00             171
28          S72.001             169
29              O80             168
30            K92.1              91

In [80]:
#diagnosis code and its description together
query = """
SELECT primary_icd10_dx,
       primary_icd10_desc,
       COUNT(*) AS Total_Claims
FROM claims
GROUP BY primary_icd10_dx, primary_icd10_desc
ORDER BY Total_Claims DESC;
"""

pd.read_sql(query, conn)

   primary_icd10_dx                      primary_icd10_desc  Total_Claims
0               I10                  Essential_hypertension          8996
1             E11.9            T2_diabetes_no_complications          7773
2             M54.5                           Low_back_pain          6251
3            M17.11       Primary_osteoarthritis_right_knee          5280
4             F32.1                            MDD_moderate          5220
5            I25.10                      CAD_without_angina          5208
6             F41.1            Generalized_anxiety_disorder          5195
7             E78.5              Hyperlipidemia_unspecified          5182
8             J18.9                   Pneumonia_unspecified          3992
9           G43.909                    Migraine_unspecified          3991
10           I48.91            Longstanding_persistent_AFib          3974
11            K21.0                   GERD_with_esophagitis          3957
12            J06.9       Acute_upper_respiratory_infection          3934
13          M25.511                     Pain_right_shoulder          3930
14            I50.9               Heart_failure_unspecified          3887
15            E66.9                     Obesity_unspecified          3867
16            J44.1                 COPD_acute_exacerbation          3856
17           C34.10  Malignant_neoplasm_upper_lobe_bronchus          2704
18            F20.9               Schizophrenia_unspecified          2695
19              G35                      Multiple_sclerosis          2679
20          S72.001              Femur_fracture_unspecified          2669
21           G89.29                      Other_chronic_pain          2660
22          C50.911         Malignant_neoplasm_right_breast          2657
23           K57.30      Diverticulosis_without_perforation          2648
24           J45.41              Moderate_persistent_asthma          2620
25           F10.20      Alcohol_use_disorder_uncomplicated          2603
26            C18.9                Malignant_neoplasm_colon          2581
27              O80                         Normal_delivery          2577
28           Z34.00            Supervision_normal_pregnancy          2576
29            A41.9                      Sepsis_unspecified          2552
30            K92.1                                  Melena          1286

PROVIDER SPECILITY ANALYSIS

In [81]:
#Total Claims by Provider Specialty
query = """
SELECT provider_specialty,
       COUNT(*) AS Total_Claims
FROM claims
GROUP BY provider_specialty
ORDER BY Total_Claims DESC;
"""

pd.read_sql(query, conn)

       provider_specialty  Total_Claims
0      Emergency_Medicine         16738
1       Internal_Medicine         14386
2              Cardiology         12078
3      Orthopedic_Surgery         10658
4       Behavioral_Health          9379
5               Radiology          8471
6                Oncology          8458
7        Gastroenterology          7410
8            Primary_Care          7313
9               Neurology          7075
10            Pulmonology          6075
11       Physical_Therapy          6038
12  Obstetrics_Gynecology          5921

In [82]:
#Total Revenue by Provider Specialty
query = """
SELECT provider_specialty,
       ROUND(SUM(claim_amount_usd),2) AS Total_Revenue
FROM claims
GROUP BY provider_specialty
ORDER BY Total_Revenue DESC;
"""

pd.read_sql(query, conn)

       provider_specialty  Total_Revenue
0      Orthopedic_Surgery  86,518,546.22
1              Cardiology  45,763,830.61
2   Obstetrics_Gynecology  29,808,134.62
3      Emergency_Medicine  21,520,019.28
4        Gastroenterology  20,946,659.34
5                Oncology  20,806,724.98
6               Radiology  16,227,334.02
7               Neurology   8,627,066.44
8             Pulmonology   7,401,028.64
9       Internal_Medicine   4,034,367.22
10      Behavioral_Health   2,342,718.96
11           Primary_Care   1,898,430.35
12       Physical_Therapy     934,901.51

In [83]:
#Average Claim Amount by Specialty
query = """
SELECT provider_specialty,
       ROUND(AVG(claim_amount_usd),2) AS Total_Revenue
FROM claims
GROUP BY provider_specialty
ORDER BY Total_Revenue DESC;
"""

pd.read_sql(query, conn)

       provider_specialty  Total_Revenue
0      Orthopedic_Surgery       8,117.71
1   Obstetrics_Gynecology       5,034.31
2              Cardiology       3,789.02
3        Gastroenterology       2,826.81
4                Oncology       2,460.01
5               Radiology       1,915.63
6      Emergency_Medicine       1,285.70
7               Neurology       1,219.37
8             Pulmonology       1,218.28
9       Internal_Medicine         280.44
10           Primary_Care         259.60
11      Behavioral_Health         249.78
12       Physical_Therapy         154.84

In [84]:
#Highest Claim Amount by Specialty
query = """
SELECT provider_specialty,
       MAX(claim_amount_usd) AS Highest_Claim
FROM claims
GROUP BY provider_specialty
ORDER BY Highest_Claim DESC;
"""

pd.read_sql(query, conn)

       provider_specialty  Highest_Claim
0      Orthopedic_Surgery      37,918.58
1              Cardiology      17,993.24
2   Obstetrics_Gynecology      15,989.34
3             Pulmonology       7,993.62
4                Oncology       7,990.24
5        Gastroenterology       6,496.32
6      Emergency_Medicine       4,999.76
7               Neurology       4,979.83
8               Radiology       4,483.94
9            Primary_Care         599.94
10      Internal_Medicine         599.57
11      Behavioral_Health         549.62
12       Physical_Therapy         279.34

In [86]:
#Lowest Claim Amount by Specialty
query = """
SELECT provider_specialty,
       MIN(claim_amount_usd) AS Highest_Claim
FROM claims
GROUP BY provider_specialty
ORDER BY Highest_Claim DESC;
"""

pd.read_sql(query, conn)

       provider_specialty  Highest_Claim
0               Radiology         260.46
1                Oncology         144.33
2        Gastroenterology         143.34
3               Neurology         143.20
4              Cardiology         117.39
5      Emergency_Medicine          97.92
6      Orthopedic_Surgery          97.77
7             Pulmonology          97.71
8       Behavioral_Health          97.70
9            Primary_Care          97.68
10  Obstetrics_Gynecology          97.60
11      Internal_Medicine          97.51
12       Physical_Therapy          52.24

In [87]:
#Paid Claims by Specialty
query = """
SELECT provider_specialty,
       COUNT(*) AS Paid_Claims
FROM claims
WHERE outcome='paid'
GROUP BY provider_specialty
ORDER BY Paid_Claims DESC;
"""

pd.read_sql(query, conn)

       provider_specialty  Paid_Claims
0      Emergency_Medicine         8729
1       Internal_Medicine         7566
2              Cardiology         6289
3      Orthopedic_Surgery         5564
4       Behavioral_Health         4842
5               Radiology         4428
6                Oncology         4359
7        Gastroenterology         3864
8            Primary_Care         3799
9               Neurology         3651
10            Pulmonology         3145
11       Physical_Therapy         3102
12  Obstetrics_Gynecology         3041

In [88]:
#Denied Claims by Specialty
query = """
SELECT provider_specialty,
       COUNT(*) AS Denied_Claims
FROM claims
WHERE outcome='denied'
GROUP BY provider_specialty
ORDER BY Denied_Claims DESC;
"""

pd.read_sql(query, conn)

       provider_specialty  Denied_Claims
0      Emergency_Medicine           4695
1       Internal_Medicine           3997
2              Cardiology           3365
3      Orthopedic_Surgery           2940
4       Behavioral_Health           2615
5                Oncology           2410
6               Radiology           2350
7        Gastroenterology           2094
8            Primary_Care           2075
9               Neurology           1998
10            Pulmonology           1733
11  Obstetrics_Gynecology           1698
12       Physical_Therapy           1694

In [89]:
#Pending Claims by Specialty
query = """
SELECT provider_specialty,
       COUNT(*) AS Pending_Claims
FROM claims
WHERE outcome='pending'
GROUP BY provider_specialty
ORDER BY Pending_Claims DESC;
"""

pd.read_sql(query, conn)

       provider_specialty  Pending_Claims
0      Emergency_Medicine            1198
1       Internal_Medicine            1018
2              Cardiology             862
3      Orthopedic_Surgery             734
4       Behavioral_Health             664
5                Oncology             633
6               Radiology             574
7               Neurology             530
8            Primary_Care             515
9        Gastroenterology             502
10       Physical_Therapy             435
11  Obstetrics_Gynecology             413
12            Pulmonology             410

In [90]:
#Denial Rate by Specialty
query = """
SELECT provider_specialty,
       COUNT(CASE WHEN outcome='denied' THEN 1 END) AS Denied_Claims,
       COUNT(*) AS Total_Claims,
       ROUND(
           COUNT(CASE WHEN outcome='denied' THEN 1 END) * 100.0 / COUNT(*),
           2
       ) AS Denial_Rate
FROM claims
GROUP BY provider_specialty
ORDER BY Denial_Rate DESC;
"""

pd.read_sql(query, conn)

       provider_specialty  Denied_Claims  Total_Claims  Denial_Rate
0   Obstetrics_Gynecology           1698          5921        28.68
1             Pulmonology           1733          6075        28.53
2                Oncology           2410          8458        28.49
3            Primary_Care           2075          7313        28.37
4        Gastroenterology           2094          7410        28.26
5               Neurology           1998          7075        28.24
6        Physical_Therapy           1694          6038        28.06
7      Emergency_Medicine           4695         16738        28.05
8       Behavioral_Health           2615          9379        27.88
9              Cardiology           3365         12078        27.86
10      Internal_Medicine           3997         14386        27.78
11              Radiology           2350          8471        27.74
12     Orthopedic_Surgery           2940         10658        27.58

In [91]:
#Revenue Lost Due to Denials
query = """
SELECT provider_specialty,
       ROUND(SUM(claim_amount_usd),2) AS Lost_Revenue
FROM claims
WHERE outcome='denied'
GROUP BY provider_specialty
ORDER BY Lost_Revenue DESC;
"""

pd.read_sql(query, conn)

       provider_specialty  Lost_Revenue
0      Orthopedic_Surgery 23,392,031.99
1              Cardiology 12,877,425.47
2   Obstetrics_Gynecology  8,446,772.62
3      Emergency_Medicine  6,008,069.30
4                Oncology  5,957,290.25
5        Gastroenterology  5,896,586.76
6               Radiology  4,520,835.57
7               Neurology  2,416,562.96
8             Pulmonology  2,048,688.38
9       Internal_Medicine  1,114,806.81
10      Behavioral_Health    654,521.83
11           Primary_Care    537,003.23
12       Physical_Therapy    261,772.90

In [ ]:
REVENUE ANALYSIS

In [92]:
#Total Revenue
query = """
SELECT ROUND(SUM(claim_amount_usd),2) AS Total_Revenue
FROM claims;
"""

pd.read_sql(query, conn)

   Total_Revenue
0 266,829,762.19

In [93]:
#Revenue by Outcome
query = """
SELECT outcome,
       ROUND(SUM(claim_amount_usd),2) AS Revenue
FROM claims
GROUP BY outcome
ORDER BY Revenue DESC;
"""

pd.read_sql(query, conn)

       outcome        Revenue
0         paid 139,055,114.84
1       denied  74,132,368.07
2  partial_pay  34,895,778.49
3      pending  18,746,500.79

In [94]:
#Revenue by Payer
query = """
SELECT payer_type,
       ROUND(SUM(claim_amount_usd),2) AS Revenue
FROM claims
GROUP BY payer_type
ORDER BY Revenue DESC;
"""

pd.read_sql(query, conn)

           payer_type       Revenue
0      Commercial_PPO 78,803,522.61
1        Medicare_FFS 53,368,320.86
2  Medicare_Advantage 45,792,265.74
3      Commercial_HMO 37,220,270.21
4    Medicaid_Managed 30,777,570.09
5      Commercial_EPO 20,867,812.68

In [95]:
#Revenue by Provider Specialty
query = """
SELECT provider_specialty,
       ROUND(SUM(claim_amount_usd),2) AS Revenue
FROM claims
GROUP BY provider_specialty
ORDER BY Revenue DESC;
"""

pd.read_sql(query, conn)

       provider_specialty       Revenue
0      Orthopedic_Surgery 86,518,546.22
1              Cardiology 45,763,830.61
2   Obstetrics_Gynecology 29,808,134.62
3      Emergency_Medicine 21,520,019.28
4        Gastroenterology 20,946,659.34
5                Oncology 20,806,724.98
6               Radiology 16,227,334.02
7               Neurology  8,627,066.44
8             Pulmonology  7,401,028.64
9       Internal_Medicine  4,034,367.22
10      Behavioral_Health  2,342,718.96
11           Primary_Care  1,898,430.35
12       Physical_Therapy    934,901.51

In [96]:
#Revenue by CPT Code
query = """
SELECT cpt_code,
       ROUND(SUM(claim_amount_usd),2) AS Revenue
FROM claims
GROUP BY cpt_code
ORDER BY Revenue DESC;
"""

pd.read_sql(query, conn)

   cpt_code       Revenue
0     27447 52,837,037.27
1     93454 27,234,339.78
2     59400 18,482,605.09
3     29827 18,464,652.62
4     29881 14,152,367.17
5     93280 11,082,127.08
6     58150 10,308,668.68
7     77301  8,273,269.51
8     96413  6,955,648.85
9     45378  6,898,242.68
10    93306  6,192,023.78
11    99285  6,082,648.72
12    31623  6,056,179.13
13    43239  5,861,558.09
14    99284  5,715,775.49
15    99291  5,590,913.36
16    43235  5,078,814.17
17    99214  4,809,961.87
18    78452  4,647,894.69
19    38220  4,567,467.58
20    70553  4,504,199.89
21    64483  4,261,523.71
22    99283  3,806,032.93
23    74177  3,329,492.15
24    99215  2,880,709.03
25    72148  2,794,971.37
26    45380  2,681,472.68
27    95819  2,427,278.71
28    99213  2,305,461.27
29    71046    950,775.92
30    95886    791,027.71
31    90837    695,818.38
32    20610    649,202.62
33    90791    647,834.19
34    76805    569,013.30
35    93000    560,369.21
36    90834    553,721.39
37    99233    458,367.48
38    99396    379,703.40
39    99232    347,555.82
40    94726    337,402.60
41    97530    308,700.71
42    97110    269,569.70
43    H0001    257,818.92
44    94010    250,602.18
45    97140    201,405.17
46    99391    162,310.21
47    97035     77,775.32
48    97012     77,450.61

In [97]:
#Revenue by ICD Code
query = """
SELECT primary_icd10_dx,
       ROUND(SUM(claim_amount_usd),2) AS Revenue
FROM claims
GROUP BY primary_icd10_dx
ORDER BY Revenue DESC;
"""

pd.read_sql(query, conn)

   primary_icd10_dx       Revenue
0               I10 19,370,032.74
1             E11.9 17,541,138.57
2             M54.5 13,846,062.96
3            M17.11 12,317,922.30
4             F41.1 11,766,477.09
5             E78.5 11,473,377.65
6             F32.1 11,163,099.41
7            I25.10 10,912,645.20
8             K21.0  8,979,584.93
9            I48.91  8,941,299.81
10          G43.909  8,928,490.25
11          M25.511  8,920,865.70
12            I50.9  8,850,784.71
13            J44.1  8,843,308.31
14            J18.9  8,804,899.04
15            J06.9  8,741,789.74
16            E66.9  8,228,894.73
17           C34.10  6,282,966.30
18           G89.29  6,067,256.57
19              O80  6,025,752.74
20          S72.001  5,911,033.97
21            A41.9  5,910,943.12
22            F20.9  5,883,544.50
23              G35  5,862,525.91
24          C50.911  5,764,302.11
25           J45.41  5,728,547.00
26           Z34.00  5,704,563.26
27            C18.9  5,688,206.81
28           K57.30  5,633,849.31
29           F10.20  5,608,694.54
30            K92.1  3,126,902.91

In [98]:
#Revenue by ICD Code
query = """
SELECT claim_quarter,
       ROUND(SUM(claim_amount_usd),2) AS Revenue
FROM claims
GROUP BY claim_quarter
ORDER BY Revenue DESC;
"""

pd.read_sql(query, conn)

  claim_quarter       Revenue
0            Q1 76,794,982.46
1            Q2 75,404,219.67
2            Q4 57,880,324.49
3            Q3 56,750,235.57

In [99]:
#Average Revenue per Claim by Payer
query = """
SELECT payer_type,
       ROUND(AVG(claim_amount_usd),2) AS Avg_Revenue
FROM claims
GROUP BY payer_type
ORDER BY Avg_Revenue DESC;
"""

pd.read_sql(query, conn)

           payer_type  Avg_Revenue
0      Commercial_PPO     2,625.38
1      Commercial_EPO     2,463.15
2      Commercial_HMO     2,407.83
3  Medicare_Advantage     2,104.62
4        Medicare_FFS     2,029.21
5    Medicaid_Managed     1,710.25

In [100]:
#Revenue Lost Due to Denials
query = """
SELECT ROUND(SUM(claim_amount_usd),2) AS Revenue_Lost
FROM claims
WHERE outcome='denied';
"""

pd.read_sql(query, conn)

   Revenue_Lost
0 74,132,368.07

In [ ]:
#Revenue Recovered (Paid Claims)
query = """
SELECT ROUND(SUM(claim_amount_usd),2) AS Revenue_Received
FROM claims
WHERE outcome='paid';
"""

pd.read_sql(query, conn)

   Revenue_Received
0    139,055,114.84

In [101]:
#Pending revenue
query = """
SELECT ROUND(SUM(claim_amount_usd),2) AS Pending_Revenue
FROM claims
WHERE outcome = 'pending';
"""

pd.read_sql(query, conn)

   Pending_Revenue
0    18,746,500.79

In [102]:
#Revenue Percentage by Payer
query = """
SELECT payer_type,
       ROUND(SUM(claim_amount_usd),2) AS Revenue,
       ROUND(
           SUM(claim_amount_usd) * 100.0 /
           (SELECT SUM(claim_amount_usd) FROM claims),
           2
       ) AS Revenue_Percentage
FROM claims
GROUP BY payer_type
ORDER BY Revenue DESC;
"""

pd.read_sql(query, conn)

           payer_type       Revenue  Revenue_Percentage
0      Commercial_PPO 78,803,522.61               29.53
1        Medicare_FFS 53,368,320.86               20.00
2  Medicare_Advantage 45,792,265.74               17.16
3      Commercial_HMO 37,220,270.21               13.95
4    Medicaid_Managed 30,777,570.09               11.53
5      Commercial_EPO 20,867,812.68                7.82

PRIOR AUTHORIZATION ANALYSIS

In [103]:
# How many claims required Prior Authorization
query = """
SELECT prior_auth_required,
       COUNT(*) AS Total_Claims
FROM claims
GROUP BY prior_auth_required;
"""

pd.read_sql(query, conn)

   prior_auth_required  Total_Claims
0                    0         65828
1                    1         54172

In [104]:
#How many claims obtained Prior Authorization
query = """
SELECT prior_auth_obtained,
       COUNT(*) AS Total_Claims
FROM claims
GROUP BY prior_auth_obtained;
"""

pd.read_sql(query, conn)

   prior_auth_obtained  Total_Claims
0                  NaN         62488
1                 0.00         10832
2                 1.00         46680

In [106]:
#Claims Required vs Obtained
query = """
SELECT
    prior_auth_required,
    prior_auth_obtained,
    COUNT(*) AS Total_Claims
FROM claims
GROUP BY prior_auth_required,
         prior_auth_obtained
ORDER BY Total_Claims DESC;
"""

pd.read_sql(query, conn)

   prior_auth_required  prior_auth_obtained  Total_Claims
0                    0                  NaN         62488
1                    1                 1.00         46680
2                    1                 0.00          7492
3                    0                 0.00          3340

In [107]:
#Denied Claims due to Missing Prior Authorization
query = """
SELECT COUNT(*) AS Denied_Claims
FROM claims
WHERE outcome='denied'
AND prior_auth_required=1
AND prior_auth_obtained=0;
"""

pd.read_sql(query, conn)

   Denied_Claims
0           5310

In [108]:
#Revenue Lost due to Missing Prior Authorization
query = """
SELECT ROUND(SUM(claim_amount_usd),2) AS Lost_Revenue
FROM claims
WHERE outcome='denied'
AND prior_auth_required=1
AND prior_auth_obtained=0;
"""

pd.read_sql(query, conn)

   Lost_Revenue
0 19,660,128.68

In [109]:
#Denial Rate based on Prior Authorization
query = """
SELECT prior_auth_obtained,
       COUNT(CASE WHEN outcome='denied' THEN 1 END) AS Denied_Claims,
       COUNT(*) AS Total_Claims,
       ROUND(
           COUNT(CASE WHEN outcome='denied' THEN 1 END) * 100.0 / COUNT(*),
           2
       ) AS Denial_Rate
FROM claims
GROUP BY prior_auth_obtained;
"""

pd.read_sql(query, conn)

   prior_auth_obtained  Denied_Claims  Total_Claims  Denial_Rate
0                  NaN          15134         62488        24.22
1                 0.00           8650         10832        79.86
2                 1.00           9880         46680        21.17

In [110]:
#Paid Claims with Prior Authorization
query = """
SELECT prior_auth_obtained,
       COUNT(*) AS Paid_Claims
FROM claims
WHERE outcome='paid'
GROUP BY prior_auth_obtained;
"""

pd.read_sql(query, conn)

   prior_auth_obtained  Paid_Claims
0                  NaN        34210
1                 1.00        28169

In [111]:
#Pending Claims with Prior Author
query = """
SELECT prior_auth_obtained,
       COUNT(*) AS Pending_Claims
FROM claims
WHERE outcome='pending'
GROUP BY prior_auth_obtained;
"""

pd.read_sql(query, conn)

   prior_auth_obtained  Pending_Claims
0                  NaN            4640
1                 0.00             806
2                 1.00            3042

In [112]:
#Revenue by Prior Authorization Status
query = """
SELECT prior_auth_obtained,
       ROUND(SUM(claim_amount_usd),2) AS Revenue
FROM claims
GROUP BY prior_auth_obtained;
"""

pd.read_sql(query, conn)

   prior_auth_obtained        Revenue
0                  NaN  63,011,278.82
1                 0.00  31,207,846.94
2                 1.00 172,610,636.43

In [113]:
#Percentage of Claims with Prior Authorization
query = """
SELECT
ROUND(
COUNT(CASE WHEN prior_auth_obtained=1 THEN 1 END)
*100.0/COUNT(*),2)
AS Prior_Auth_Percentage
FROM claims;
"""

pd.read_sql(query, conn)

   Prior_Auth_Percentage
0                  38.90